CREATE TYPE EMPLEADO_T AS OBJECT (
NOMBRE VARCHAR2(30),
JEFE REF EMPLEADO_T
);
/

CREATE TABLE EMPLEADO OF EMPLEADO_T;
/

INSERT INTO EMPLEADO VALUES (EMPLEADO_T('GIL', NULL));
/

INSERT INTO EMPLEADO 
SELECT EMPLEADO_T ('ARROYO', REF(E))
FROM EMPLEADO E WHERE E.NOMBRE = 'GIL';
/

INSERT INTO EMPLEADO 
SELECT EMPLEADO_T ('RAMOS', REF(E))
FROM EMPLEADO E WHERE E.NOMBRE = 'GIL';
/

SELECT NOMBRE, P.JEFE.nombre FROM EMPLEADO P;
/

UPDATE EMPLEADO
SET JEFE = (SELECT REF(E) FROM EMPLEADO E WHERE NOMBRE='ARROYO')
WHERE NOMBRE='RAMOS'
/