CREATE TYPE TABLA_ANIDADA AS TABLE OF DIRECCION;
/

CREATE TABLE EJEMPLO_TABLA_ANIDADA 
(
 ID NUMBER(2),
 APELLIDOS VARCHAR2(35),
 DIREC TABLA_ANIDADA
)
NESTED TABLE DIREC STORE AS DIREC_ANIDADA;
/

INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES (1, 'RAMOS', 
  TABLA_ANIDADA (
    DIRECCION ('C/Los manantiales 5', 'GUADALAJARA', 19004),
    DIRECCION ('C/Los manantiales 10', 'GUADALAJARA', 19004),
    DIRECCION ('C/Av de Paris 25', 'CÁCERES', 10005),
    DIRECCION ('C/Segovia 23-3A', 'TOLEDO', 45005)
  )
);
/

INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES (2, 'MARTÍN', 
  TABLA_ANIDADA (
    DIRECCION ('C/Huesca 5', 'ALCALÁ DE H', 28804),
    DIRECCION ('C/Madrid 20', 'ALCORCÓN', 28921)
  )
);
/

INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES (5, 'PEREZ', TABLA_ANIDADA());
/

SELECT * FROM EJEMPLO_TABLA_ANIDADA;
/

SELECT ID, APELLIDOS, d.*, d.calle
FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) d;
/

SELECT  ID, DIRECCION.* 
FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) DIRECCION WHERE ID=1;
/

SELECT ID, APELLIDOS, CURSOR(SELECT count(*) FROM TABLE(DIREC) )
FROM EJEMPLO_TABLA_ANIDADA;
/

SELECT ID, APELLIDOS, count(*)
FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC)
GROUP BY ID, APELLIDOS;
/

SELECT ID, APELLIDOS, CURSOR (SELECT COUNT(*) FROM  TABLE(DIREC) WHERE CIUDAD ='GUADALAJARA')
FROM EJEMPLO_TABLA_ANIDADA
WHERE (SELECT COUNT(*) FROM TABLE(DIREC) WHERE CIUDAD ='GUADALAJARA') = 2;
/

SELECT ID, APELLIDOS, COUNT(*)
FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) 
WHERE CIUDAD ='GUADALAJARA' 
GROUP BY ID, APELLIDOS 
HAVING COUNT(*) = 2;
/

SELECT * FROM THE (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = 2);
/

SELECT TT.* FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) TT WHERE ID=2;
/

declare
--id  Apellido  Calle Ciudad  Cod postal
   cursor c1 is select id, apellidos from ejemplo_tabla_anidada;
   cursor c2(idape number) is select 
           ciudad, calle,cODIGO_POST from the (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = idape );
          
begin
   for  r1 in c1 loop
       dbms_output.put_line('ID: ' ||r1.id||'.     Apellido: '||r1.apellidos);
       dbms_output.put_line(' '|| ' Calle'||' '|| 'Ciudad'||' '||'CODIGO_POST');
      dbms_output.put_line(' '|| ' -----'||' '|| '------'||' '||'------------');
      for r2 in c2(r1.id) loop
            dbms_output.put_line(' '|| r2.calle||' '|| r2.ciudad||' '||r2.codigo_post);   
      end loop;
   end loop;
end;
/

INSERT INTO TABLE (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = 5) 
VALUES (DIRECCION ('C/Los manantiales 15', 'GUADALAJARA', 19004));
/

UPDATE TABLE (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = 1) PRIMERA
SET VALUE(PRIMERA) = DIRECCION ('C/Pilon 11', 'TOLEDO', 45589)
WHERE VALUE(PRIMERA) = DIRECCION('C/Los manantiales 5', 'GUADALAJARA', 19004);
/

UPDATE TABLE (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = 1) PRIMERA
SET PRIMERA.CIUDAD =  'MADRID'
WHERE PRIMERA.CIUDAD = 'GUADALAJARA';
/

DELETE FROM TABLE (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = 1) PRIMERA
WHERE VALUE(PRIMERA)=DIRECCION('C/Los manantiales 10', 'GUADALAJARA', 19004);
/

DELETE FROM TABLE (SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID = 1) PRIMERA
WHERE PRIMERA.CIUDAD ='GUADALAJARA';
/

CREATE OR REPLACE PROCEDURE VER_DIREC(IDENT NUMBER) AS
 CURSOR C1 IS SELECT CALLE FROM THE (SELECT T.DIREC FROM EJEMPLO_TABLA_ANIDADA T WHERE ID = IDENT);
BEGIN
  FOR I IN C1 LOOP
    DBMS_OUTPUT.PUT_LINE(I.CALLE);
  END LOOP;
END VER_DIREC;
/

--Probando el procedimiento
BEGIN
  VER_DIREC(1);
END;
/
