-- CREO LOS TIPOS
-- PASAJERO
CREATE TYPE TIPOPASAJERO AS OBJECT(
    COD smallint,
	NOMBRE varchar(30),
	TLF varchar(10),
	DIRECCION varchar(40),
	PAIS varchar(15)
);
/
-- PERSONAL
CREATE TYPE TIPOPERSONAL AS OBJECT(
    CODIGO smallint,
	NOMBRE varchar(20),
	CATEGORIA varchar(15),
    PUESTO varchar(10)
);
/
-- PASAJE
CREATE TYPE TIPOPASAJE AS OBJECT(
    PASAJERO REF TIPOPASAJERO, -- REFERENCIA A UN PASAJERO (TIPOPASAJERO)
	NUMASIENTO smallint,
	CLASE varchar(10),
	PVP float
);
/
-- VUELO, CONTIENE 2 TABLAS ANIDADAS POR LOS QUE TENGO QUE CREARLAS ANTES
-- ANIDADA TIPOPASAJE
CREATE TYPE TABLA_TIPOPASAJE AS TABLE OF TIPOPASAJE;
/
-- ANIDADA TIPOPERSONAL
CREATE TYPE TABLA_TIPOPERSONAL AS TABLE OF TIPOPERSONAL;
/

-- AHORA SI CREO EL TIPO VUELO
CREATE OR REPLACE TYPE TIPOVUELO  AS OBJECT(
    IDENTIFICADOR varchar(10),
	AEROPUERTO_ORIGEN varchar(10),
	AEROPUERTO_DESTINO varchar(10),
	TIPO_VUELO varchar(15),
	FECHA_VUELO date,
    
    PASAJEROS TABLA_TIPOPASAJE, -- TABLA ANIDADA PASAJEROS
    PERSONAL TABLA_TIPOPERSONAL, -- TABLA ANIDADA PERSONAL
    
    MEMBER FUNCTION SUMA RETURN NUMBER,
    MEMBER FUNCTION NPASACLASE(PAIS VARCHAR2, CLASE VARCHAR2) RETURN NUMBER
);
/

-- CREO UNA TABLA DE OBJECTOS TIPOVUELO CON LAS DOS TABLAS ANIDADAS
CREATE TABLE TABLA_TIPOVUELO OF TIPOVUELO(
    IDENTIFICADOR PRIMARY KEY
)
NESTED TABLE PASAJEROS STORE AS TABLA_PASAJEROS
NESTED TABLE PERSONAL STORE AS TABLA_PERSONAL
;
/

-- HORA DE LLENAR LA TABLA
-- PRIMERO LLENO LOS DATOS DE VUELOS CON LAS TABLAS ANIDADAS VACIAS, UTILIZO LA TABLA VUELO QUE YA TENGO
INSERT INTO TABLA_TIPOVUELO 
    SELECT IDENTIFICADOR, AEROPUERTO_ORIGEN, AEROPUERTO_DESTINO, TIPO_VUELO, FECHA_VUELO, TABLA_TIPOPASAJE(), TABLA_TIPOPERSONAL() 
    FROM VUELO
;
/

-- AHORA CREO UN PROCEDURE PARA LLENAR LA TABLA ANIDADA DE PASAJE
-- PERO ANTES DE ESO TENGO QUE HACER UNA TABLA DE TIPOPASAJERO PORQUE EL PASAJE TIENE UNA REFERENCIA A UN OBJECTO PASAJERO
CREATE TABLE TABLA_TIPOPASAJERO OF TIPOPASAJERO(
    COD PRIMARY KEY
);
/

-- Y AHORA LA RELLENO
INSERT INTO TABLA_TIPOPASAJERO
    SELECT * FROM PASAJERO;
/

-- AHORA SI CREO EL PROCEDURE
CREATE OR REPLACE PROCEDURE LLENAR_PASAJES IS
    CURSOR VUELOS IS SELECT * FROM VUELO; -- COJO TODOS LOS VUELO
    CURSOR PASAJES(IDE VARCHAR2) IS SELECT * FROM PASAJE WHERE IDENTIFICADOR = IDE; -- COJO LOS PASAJES DE UN VUELO EN CONCRETO
    
    TABLA_PASAJES TABLA_TIPOPASAJE; -- UNA TABLA VACIA
    PASAJE TIPOPASAJE; -- UN OBJECTO TIPOPASAJE VACIO   
    PASA REF TIPOPASAJERO; -- UNA REFERENCIA A UN OBJECTO TIPOPASAJERO VACIO
BEGIN
    FOR V IN VUELOS LOOP -- RECORRO LOS VUELO
        TABLA_PASAJES := TABLA_TIPOPASAJE(); -- PONGO LA TABLA VACIA AL PRINCIPIO DE CADA ITERACION
        
        FOR P IN PASAJES(V.IDENTIFICADOR) LOOP -- RECORRO LOS PASAJES DE ESE VUELO
            SELECT REF(P) INTO PASA FROM TABLA_TIPOPASAJERO P WHERE COD = P.PASAJERO_COD; -- COJO UNA REFERENCIA A UN OBJETO TIPOPASAJERO QUE TENGA ESE PASAJE
            PASAJE := TIPOPASAJE(PASA, P.NUMASIENTO, P.CLASE, P.PVP); -- CREO EL OBJECTO TIPOPASAJE CON LA REFERENCIA Y LOS DATOS DEL PASAJE
            
            TABLA_PASAJES.EXTEND; -- AÑADO UN HUECO A LA TABLA
            TABLA_PASAJES(TABLA_PASAJES.COUNT) := PASAJE; -- LE INSERTO EL OBJECTO TIPOPASAJA A LA TABLA
        END LOOP;
        
        UPDATE TABLA_TIPOVUELO SET PASAJEROS = TABLA_PASAJES WHERE IDENTIFICADOR = V.IDENTIFICADOR; -- ACTUALIZO LA TABLA ANIDADA DE ESE VUELO CON LA NUEVA TABLA QUE HE RELLENADO
    END LOOP;
END;
/

-- LO EJECUTO
BEGIN
    LLENAR_PASAJES();
END;
/

-- AHORA LA TABLA ANIDADA PERSONAL
-- ESTA ES MAS FACIL PORQUE NO TIENE REFERENCIAS
CREATE OR REPLACE PROCEDURE LLENAR_PERSONAL IS
    CURSOR VUELOS IS SELECT * FROM VUELO;
    CURSOR PERSONAL(IDE VARCHAR2) IS SELECT CODIGO, NOMBRE, CATEGORIA, PUESTO FROM PERSONAL JOIN TRIPULACION ON CODIGO = PERSONAL_CODIGO WHERE VUELO_IDENTIFICADOR = IDE;
    
    TABLA_PERSONAL TABLA_TIPOPERSONAL;
    PERSONA TIPOPERSONAL;
BEGIN
    FOR V IN VUELOS LOOP
        TABLA_PERSONAL := TABLA_TIPOPERSONAL();
        FOR P IN PERSONAL(V.IDENTIFICADOR) LOOP
            PERSONA := TIPOPERSONAL(P.CODIGO, P.NOMBRE, P.CATEGORIA, P.PUESTO);
            
            TABLA_PERSONAL.EXTEND;
            TABLA_PERSONAL(TABLA_PERSONAL.COUNT) := PERSONA;
        END LOOP;
        
        UPDATE TABLA_TIPOVUELO SET PERSONAL = TABLA_PERSONAL WHERE IDENTIFICADOR = V.IDENTIFICADOR;
    END LOOP;
END;
/

-- Y LO PRUEBO
BEGIN
    LLENAR_PERSONAL();
END;
/

-- CONSULTAS
SELECT DEREF(P.PASAJERO).NOMBRE FROM TABLA_TIPOVUELO V, TABLE(V.PASAJEROS) P 
WHERE DEREF(P.PASAJERO).PAIS = 'ESPA?A' AND V.AEROPUERTO_ORIGEN LIKE '%MAD%';
/

SELECT IDENTIFICADOR, AEROPUERTO_ORIGEN, AEROPUERTO_DESTINO, TIPO_VUELO, COUNT(*), V.SUMA() FROM TABLA_TIPOVUELO V, TABLE(V.PASAJEROS) P
GROUP BY IDENTIFICADOR, AEROPUERTO_ORIGEN, AEROPUERTO_DESTINO, TIPO_VUELO, V.SUMA();
/

SELECT IDENTIFICADOR, AEROPUERTO_ORIGEN, AEROPUERTO_DESTINO, TIPO_VUELO, V.NPASACLASE('ESPA?A', 'TURISTA') 
FROM TABLA_TIPOVUELO V;
/











