CREATE TYPE TIPO_DEP AS OBJECT (
    DEPT_NO NUMBER(2),
    DNOMBRE VARCHAR2(15),
    LOC VARCHAR2(15)
);
/

CREATE TABLE DEPART OF TIPO_DEP;
/

INSERT INTO DEPART
SELECT dept_no, dnombre, loc FROM departamentos;
/

CREATE TABLE EMPLEDEPART (
    EMP_NO NUMBER(4) PRIMARY KEY,
    APELLIDO VARCHAR2(15),
    SALARIO NUMBER(6,2),
    DEPT REF TIPO_DEP
);
/

--LLENAR ESTA TABLA CON LOS DATOS DEL EMPLEADO Y LA REF AL DEPARTAMENTO
INSERT INTO EMPLEDEPART
SELECT emp_no, apellido, salario, REF(d) FROM empleados JOIN depart d USING(dept_no);
/

SELECT * FROM empledepart e WHERE e.dept.dept_no = 10;
/

SELECT EMP_NO, APELLIDO, SALARIO, e.DEPT.DEPT_NO, e.DEPT.DNOMBRE, e.DEPT.LOC FROM empledepart e;
/

DECLARE
    CURSOR DEPARTAMENTOS IS SELECT * FROM depart D;
    CURSOR EMPLEADOS(D NUMBER) IS SELECT * FROM empledepart E WHERE E.DEPT.DEPT_NO = D;
BEGIN
    FOR DEPT IN DEPARTAMENTOS LOOP
        DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO: ' || DEPT.DEPT_NO || ' ' || DEPT.DNOMBRE || ' ' || DEPT.LOC);
        FOR EMP IN EMPLEADOS(DEPT.DEPT_NO) LOOP
            DBMS_OUTPUT.PUT_LINE('    EMPLEADO: ' || EMP.EMP_NO || ' ' || EMP.APELLIDO || ' ' || EMP.SALARIO);
        END LOOP;
    END LOOP;
END;
/
